title:              Wedge Head Skunk
email:              wedgeheadskunk@gmail.com
description:        A newsletter about food and technology
author:             Jim Partee
baseurl:            "/home"
url:                "http://wedgeheadskunk.com"

# Social Profiles
twitter_username:   wedgeheadskunk
github_username:    jimpartee
facebook_username:
instagram_username:
linkedin_username: jim-partee

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

theme: jekyll-theme-clean-blog